FROM node:18-alpine3.18

WORKDIR /app

RUN apk add --no-cache sqlite sqlite-dev


RUN npm install -g pnpm

COPY Back/prisma .

RUN pnpm install


ENV DATABASE_URL="file:./prisma/data/test.sqlite"

EXPOSE 5555
