services:
  
  backend:
    build:
      context: .
      dockerfile: Back/Dockerfile.devback
    container_name: transcendance-back-dev
    volumes:
      - ./Back:/app
      - ./Shared:/app/Shared
    command: sh -c "pnpm install && pnpm run dev:server"


  frontend:
    build:
      context: .
      dockerfile: Front/Dockerfile.devfront
    container_name: transcendance-front-dev
    volumes:
      - ./Front:/app      
      - ./Shared:/app/Shared
    command: sh -c "pnpm install && pnpm run dev"


  studio:
    build:
      context: .
      dockerfile: Back/prisma/Dockerfile.studio
    container_name: transcendance-studio
    depends_on:
      - backend
    ports:
      - "5555:5555"
    volumes:
      - prisma_data:/app/data
    environment:
      - DATABASE_URL=file:./Back/prisma/data/test.sqlite
    command: pnpx prisma studio --schema=./schema.prisma

  nginx:
    build:
      context: .
      dockerfile: Nginx/Dockerfile.nginx
    container_name: transcendance-nginx
    ports:
      - "8443:443"
      - "8080:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - shared_code:/app/Shared
      - ssl_certs:/etc/nginx/certs

volumes:
  prisma_data:
  shared_code:
  ssl_certs: