

x-buildkit: &buildkit-args
  args:
    - DOCKER_BUILDKIT=1

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.back
      <<: *buildkit-args
    container_name: transcendance-back
    working_dir: /app
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app/server
      - ./prisma:/app/prisma
      - ./ssl:/app/ssl
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.front
      <<: *buildkit-args
    container_name: transcendance-front
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development

  nginx:
    image: nginx:latest
    ports:
      - "8443:443"
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/certs:ro
    depends_on:
      - frontend

  studio:
    build:
      context: .
      dockerfile: Dockerfile.studio
      <<: *buildkit-args
    container_name: transcendance-studio
    working_dir: /app
    ports:
      - "5555:5555"
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    environment:
      - DATABASE_URL=file:./prisma/data/test.sqlite
    depends_on:
      - backend

volumes:
  node_modules:
