x-buildkit: &buildkit-args
  args:
    - DOCKER_BUILDKIT=1

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.back
      <<: *buildkit-args
    container_name: transcendance-back
    working_dir: /app
    ports:
      - "3001:3001"
    volumes:
      - backend_server_data:/app/server
      - backend_prisma_data:/app/prisma
      - backend_ssl_data:/app/ssl
      - backend_profilepicture_data:/app/public/profilepicture
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.front
      <<: *buildkit-args
    container_name: transcendance-front
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - frontend_app_data:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8443:443"
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/certs
      - ./generate_ssl.sh:/usr/local/bin/generate_ssl.sh
    depends_on:
      - frontend
    entrypoint: ["/bin/sh", "/usr/local/bin/generate_ssl.sh"]

  studio:
    build:
      context: .
      dockerfile: Dockerfile.studio
      <<: *buildkit-args
    container_name: transcendance-studio
    working_dir: /app
    ports:
      - "5555:5555"
    volumes:
      - studio_app_data:/app
      - node_modules:/app/node_modules
    environment:
      - DATABASE_URL=file:./prisma/data/test.sqlite
    depends_on:
      - backend

volumes:
  node_modules:
  backend_server_data:
  backend_prisma_data:
  backend_ssl_data:
  backend_profilepicture_data:
  frontend_app_data:
  studio_app_data:
