x-buildkit: &buildkit-args # meilleurs perf de build
  args:
    - DOCKER_BUILDKIT=1 # active buildkit

services:
  backend:
    build:
      context: .  # L endroit d ou on va build + pouvoir use les fichier le cpy et use le dockerfile.   
      dockerfile: Dockerfile.back
      <<: *buildkit-args
    container_name: transcendance-back
    working_dir: /app # la ou on va exec les cmds
    ports:
      - "3001:3001" # gauche = ma machine, droite = le container.
    volumes: # donnes persistentes. non bind-mount ici car declarer dans volumes en bas (donc pas co a ma machine : faut rebuild si changement)
      - backend_data:/app/server
      - prisma_data:/app/prisma
      - ssl_data:/app/ssl
    environment: #var environnement.
      - NODE_ENV=development

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.front
      <<: *buildkit-args
    container_name: transcendance-front
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - frontend_data:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8443:443" #port standard https
    volumes:
      - nginx_conf:/etc/nginx/conf.d/default.conf
      - ssl_data:/etc/nginx/certs
    depends_on:
      - frontend

  studio:
    build:
      context: .
      dockerfile: Dockerfile.studio
      <<: *buildkit-args
    container_name: transcendance-studio
    working_dir: /app
    ports:
      - "5555:5555"
    volumes:
      - studio_data:/app
      - node_modules:/app/node_modules
    environment:
      - DATABASE_URL=file:./prisma/data/test.sqlite
    depends_on:
      - backend

volumes: # gerer par docker + shared entre les containers.
  node_modules:
  backend_data:
  prisma_data:
  ssl_data:
  nginx_conf:
  studio_data:
