services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transcendance-back
    working_dir: /app
    command: ["sh", "-c", "pnpm run generate-prisma && pnpm run dev:server"]
    ports:
      - "3001:3001"
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transcendance-front
    working_dir: /app
    command: ["pnpm", "run", "dev"]
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development

  studio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transcendance-studio
    working_dir: /app
    command: ["pnpx", "prisma", "studio"]
    ports:
      - "5555:5555"
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    environment:
      - DATABASE_URL=file:./prisma/data/test.sqlite
    depends_on:
      - backend

volumes:
  node_modules:
