FROM node:18-alpine3.18

WORKDIR /app

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY buildEnv.sh ./
RUN ./buildEnv.sh

COPY . .

EXPOSE 3000

CMD ["pnpm", "run", "dev"]
