FROM node:18-alpine3.18

WORKDIR /app
RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY server/ ./server
COPY prisma/ ./prisma

RUN pnpm run generate-prisma

COPY . .

EXPOSE 3001


CMD ["pnpm", "run", "dev:server"]
