services:
  
  backend:
    build:
      context: .
      dockerfile: Back/Dockerfile.devback
    container_name: transcendance-back-dev
    ports:
      - "3001:3001"
    volumes:
      - ./Back/server:/app/server
      - ./Back/prisma:/app/prisma
      - ./Back/config:/app/config
      - ./Back/package.json:/app/package.json
      - ./Back/pnpm-lock.yaml:/app/pnpm-lock.yaml
      - ./Back/tsconfig.json:/app/tsconfig.json
      - ./Shared:/app/Shared
      - ssl_certs:/app/Shared/certs
    command: sh -c "pnpm install && pnpx prisma generate --schema=./prisma/schema.prisma && pnpx prisma db push --schema=./prisma/schema.prisma && pnpm run dev:server"


  frontend:
    build:
      context: .
      dockerfile: Front/Dockerfile.devfront
    container_name: transcendance-front-dev
    volumes:
      - ./Front:/app      
      - ./Shared:/app/Shared
    command: sh -c "ln -sf /app/Shared/public /app/public && pnpm install && pnpm run dev"


  studio:
    build:
      context: .
      dockerfile: Back/prisma/Dockerfile.studio
    container_name: transcendance-studio
    depends_on:
      - backend
    ports:
      - "5555:5555"
    volumes:
      - ./Back/prisma:/app
    environment:
      - DATABASE_URL=file:./data/test.sqlite
    command: pnpx prisma studio --schema=./schema.prisma

  nginx:
    build:
      context: .
      dockerfile: Nginx/Dockerfile.nginx
    container_name: transcendance-nginx
    ports:
      - "8443:443"
      - "8080:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./Shared:/app/Shared
      - ssl_certs:/etc/nginx/certs

volumes:
  ssl_certs: