FROM node:18-alpine3.18

WORKDIR /app

# Installer sqlite et sqlite-dev avec apk
RUN apk add --no-cache sqlite sqlite-dev

RUN npm install -g pnpm

# Copier package.json d'abord
COPY Back/package.json Back/pnpm-lock.yaml* ./

RUN pnpm install

# Puis copier le reste des fichiers
COPY Back/ .
COPY Shared/ ./Shared/

RUN pnpx prisma generate --schema=./prisma/schema.prisma

EXPOSE 3001

CMD ["pnpm", "run", "dev:server"]




