FROM nginx:alpine

RUN apk add --no-cache openssl

COPY Nginx/default.conf /etc/nginx/conf.d/default.conf
COPY Nginx/generate_ssl.sh /etc/nginx/generate_ssl.sh

RUN chmod +x /etc/nginx/generate_ssl.sh

# Créer le dossier pour les certificats
RUN mkdir -p /etc/nginx/certs

ENTRYPOINT ["/etc/nginx/generate_ssl.sh"]
