FROM nginx:alpine

RUN apk add --no-cache openssl

COPY nginx/default.conf /etc/nginx/conf.d/default.conf
COPY nginx/generate_ssl.sh /etc/nginx/generate_ssl.sh

RUN chmod +x /etc/nginx/generate_ssl.sh

# Lien symbolique pour les certificats partagés
RUN ln -sf /app/Shared/certs /etc/nginx/certs

ENTRYPOINT ["/etc/nginx/generate_ssl.sh"]
